/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Invoice resources.
         * @description Retrieves the collection of Invoice resources.
         */
        get: operations["api_invoices_get_collection"];
        put?: never;
        /**
         * Creates a Invoice resource.
         * @description Creates a Invoice resource.
         */
        post: operations["api_invoices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Invoice resource.
         * @description Retrieves a Invoice resource.
         */
        get: operations["api_invoices_id_get"];
        /**
         * Replaces the Invoice resource.
         * @description Replaces the Invoice resource.
         */
        put: operations["api_invoices_id_put"];
        post?: never;
        /**
         * Removes the Invoice resource.
         * @description Removes the Invoice resource.
         */
        delete: operations["api_invoices_id_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{id}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue the invoice.
         * @description Issue the invoice.
         */
        post: operations["api_invoices_idissue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{id}/mark_paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark the invoice as paid.
         * @description Mark the invoice as paid.
         */
        post: operations["api_invoices_idmark_paid_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The issued invoice as a PDF, base64 encoded.
         * @description The issued invoice as a PDF, base64 encoded.
         */
        get: operations["api_invoices_idpdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Unprocessable entity */
        ConstraintViolation: {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: {
                    [key: string]: unknown;
                };
            }[];
            readonly detail?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description Unprocessable entity */
        "ConstraintViolation.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: {
                    [key: string]: unknown;
                };
            }[];
            readonly detail?: string;
            readonly description?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description A representation of common errors. */
        Error: {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
        };
        /** @description A representation of common errors. */
        "Error.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
            readonly description?: string | null;
        };
        HydraCollectionBaseSchema: components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
            /**
             * @example {
             *       "@id": "string",
             *       "@type": "string",
             *       "first": "string",
             *       "last": "string",
             *       "previous": "string",
             *       "next": "string"
             *     }
             */
            view?: {
                /** Format: iri-reference */
                "@id"?: string;
                "@type"?: string;
                /** Format: iri-reference */
                first?: string | null;
                /** Format: iri-reference */
                last?: string | null;
                /** Format: iri-reference */
                previous?: string | null;
                /** Format: iri-reference */
                next?: string | null;
            };
        };
        HydraCollectionBaseSchemaNoPagination: {
            totalItems?: number;
            search?: {
                "@type"?: string;
                template?: string;
                variableRepresentation?: string;
                mapping?: {
                    "@type"?: string;
                    variable?: string;
                    property?: string | null;
                    required?: boolean;
                }[];
            };
        };
        HydraItemBaseSchema: {
            "@context"?: string | ({
                "@vocab": string;
                /** @enum {string} */
                hydra: "http://www.w3.org/ns/hydra/core#";
            } & {
                [key: string]: unknown;
            });
            "@id": string;
            "@type": string;
        };
        "Invoice.InvoiceInput": {
            clientName: string;
            clientAddress: string;
            clientCompanyId: string;
            clientVatId?: string | null;
            dueAt: string;
            taxPointAt: string;
            note?: string | null;
            items?: components["schemas"]["InvoiceItemInput"][];
        };
        "Invoice.InvoicePdf.jsonld-invoice_pdf.read": components["schemas"]["HydraItemBaseSchema"] & {
            name: string;
            base64Content: string;
        };
        "Invoice.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** Format: ulid */
            id: string;
            readonly number: string | null;
            /**
             * @default draft
             * @enum {string}
             */
            readonly status: "draft" | "issued";
            clientName: string;
            clientAddress: string;
            clientCompanyId: string;
            clientVatId: string | null;
            readonly supplierName: string | null;
            readonly supplierAddress: string | null;
            readonly supplierCompanyId: string | null;
            readonly supplierVatId: string | null;
            readonly supplierBankAccount: string | null;
            /** @description Required on a company's invoice by § 435 občanského zákoníku. */
            readonly supplierRegisterEntry: string | null;
            /** Format: date-time */
            readonly issuedAt: string | null;
            /** Format: date-time */
            dueAt: string;
            /**
             * Format: date-time
             * @description The tax point, DUZP on a Czech document.
             */
            taxPointAt: string;
            /** Format: date-time */
            readonly paidAt: string | null;
            note: string | null;
            items: components["schemas"]["InvoiceItem.jsonld"][];
            readonly variableSymbol: string | null;
            readonly vatSummary: components["schemas"]["VatSummaryLine.jsonld"][];
            readonly totalNetAmount: number;
            readonly totalVatAmount: number;
            readonly totalGrossAmount: number;
        };
        "Invoice.jsonld-invoice.read_invoice.operation.get": components["schemas"]["HydraItemBaseSchema"] & {
            /** Format: ulid */
            id: string;
            readonly number: string | null;
            /**
             * @default draft
             * @enum {string}
             */
            readonly status: "draft" | "issued";
            clientName: string;
            clientAddress: string;
            clientCompanyId: string;
            clientVatId: string | null;
            readonly supplierName: string | null;
            readonly supplierAddress: string | null;
            readonly supplierCompanyId: string | null;
            readonly supplierVatId: string | null;
            readonly supplierBankAccount: string | null;
            /** @description Required on a company's invoice by § 435 občanského zákoníku. */
            readonly supplierRegisterEntry: string | null;
            /** Format: date-time */
            readonly issuedAt: string | null;
            /** Format: date-time */
            dueAt: string;
            /**
             * Format: date-time
             * @description The tax point, DUZP on a Czech document.
             */
            taxPointAt: string;
            /** Format: date-time */
            readonly paidAt: string | null;
            note: string | null;
            items: components["schemas"]["InvoiceItem.jsonld-invoice.read_invoice.operation.get"][];
            readonly variableSymbol: string | null;
            readonly vatSummary: components["schemas"]["VatSummaryLine.jsonld-invoice.read_invoice.operation.get"][];
            readonly totalNetAmount: number;
            readonly totalVatAmount: number;
            readonly totalGrossAmount: number;
        };
        "Invoice.jsonld-invoice.read_invoice.operation.get_collection": components["schemas"]["HydraItemBaseSchema"] & {
            /** Format: ulid */
            id: string;
            readonly number: string | null;
            /**
             * @default draft
             * @enum {string}
             */
            readonly status: "draft" | "issued";
            clientName: string;
            /** Format: date-time */
            readonly issuedAt: string | null;
            /** Format: date-time */
            dueAt: string;
            /** Format: date-time */
            readonly paidAt: string | null;
            items: components["schemas"]["InvoiceItem.jsonld-invoice.read_invoice.operation.get_collection"][];
            readonly totalGrossAmount: number;
        };
        "InvoiceItem.jsonld": {
            /** Format: ulid */
            id: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            invoice: string;
            description: string;
            /** Format: string */
            quantity: string;
            unit: string;
            /** @enum {string} */
            vatRate: "21" | "12" | "0";
            unitPriceNet: number;
            readonly netAmount: number;
        };
        "InvoiceItem.jsonld-invoice.read_invoice.operation.get": {
            /** Format: ulid */
            id: string;
            description: string;
            /** Format: string */
            quantity: string;
            unit: string;
            /** @enum {string} */
            vatRate: "21" | "12" | "0";
            unitPriceNet: number;
            readonly netAmount: number;
        };
        "InvoiceItem.jsonld-invoice.read_invoice.operation.get_collection": {
            /** Format: ulid */
            id: string;
            description: string;
            /** Format: string */
            quantity: string;
            unit: string;
            /** @enum {string} */
            vatRate: "21" | "12" | "0";
            unitPriceNet: number;
            readonly netAmount: number;
        };
        InvoiceItemInput: {
            /** Format: ulid */
            id?: string | null;
            description: string;
            quantity: string;
            unit: string;
            unitPriceNet: number;
            /** @enum {string} */
            vatRate: "21" | "12" | "0";
        };
        "VatSummaryLine.jsonld": {
            /** @enum {string} */
            vatRate: "21" | "12" | "0";
            netAmount: number;
            vatAmount: number;
            grossAmount: number;
        };
        "VatSummaryLine.jsonld-invoice.read_invoice.operation.get": {
            /** @enum {string} */
            vatRate: "21" | "12" | "0";
            netAmount: number;
            vatAmount: number;
            grossAmount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_invoices_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
                "order[number]"?: "asc" | "desc";
                "order[clientName]"?: "asc" | "desc";
                "order[issuedAt]"?: "asc" | "desc";
                "order[dueAt]"?: "asc" | "desc";
                "order[paidAt]"?: "asc" | "desc";
                "order[status]"?: "asc" | "desc";
                clientName?: string;
                status?: "draft" | "issued";
                "status[]"?: ("draft" | "issued")[];
                "exists[paidAt]"?: boolean;
                "issuedAt[before]"?: string;
                "issuedAt[strictly_before]"?: string;
                "issuedAt[after]"?: string;
                "issuedAt[strictly_after]"?: string;
                "dueAt[before]"?: string;
                "dueAt[strictly_before]"?: string;
                "dueAt[after]"?: string;
                "dueAt[strictly_after]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Invoice.jsonld-invoice.read_invoice.operation.get_collection"][];
                    };
                };
            };
        };
    };
    api_invoices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Invoice resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Invoice.InvoiceInput"];
            };
        };
        responses: {
            /** @description Invoice resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Invoice.jsonld-invoice.read_invoice.operation.get"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_invoices_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invoice identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Invoice.jsonld-invoice.read_invoice.operation.get"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_invoices_id_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invoice identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Invoice resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Invoice.InvoiceInput"];
            };
        };
        responses: {
            /** @description Invoice resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Invoice.jsonld-invoice.read_invoice.operation.get"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_invoices_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invoice identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_invoices_idissue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invoice identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice resource created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Invoice.jsonld-invoice.read_invoice.operation.get"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_invoices_idmark_paid_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invoice identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice resource created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Invoice.jsonld-invoice.read_invoice.operation.get"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_invoices_idpdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invoice identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Invoice.InvoicePdf.jsonld-invoice_pdf.read"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
